param([ValidatePattern('^[a-z0-9][a-z0-9-]{0,40}$')][string]$Instance='cs-client-a',
      [ValidateSet('neoforge','fabric')][string]$Loader='neoforge')
. (Join-Path $PSScriptRoot 'SandboxPaths.ps1')
$cluster=Get-Content -LiteralPath (Join-Path $script:GoldCraftRoot 'sandbox/cluster.json') -Raw | ConvertFrom-Json
$serverName=if($Loader -eq 'neoforge'){'sandbox/neoforge-server'}else{'sandbox/mc-server'}
$clientName=if($Loader -eq 'neoforge'){"sandbox/neoforge-$Instance"}else{"sandbox/minecraft-$Instance"}
$server=Assert-SandboxPath (Join-Path $script:GoldCraftRoot $serverName)
$client=Assert-SandboxPath (Join-Path $script:GoldCraftRoot $clientName)
foreach($directory in @($server,$client)){New-Item -ItemType Directory -Path $directory -Force | Out-Null}
$properties=Join-Path $server 'server.properties'
if(-not(Test-Path -LiteralPath $properties)){
    @"
# Isolated loopback-only $Loader development server; generated by GoldCraft tools.
server-ip=127.0.0.1
server-port=$($cluster.minecraftPort)
online-mode=false
enforce-secure-profile=false
enable-rcon=true
rcon.port=$($cluster.minecraftRconPort)
rcon.password=$($cluster.rconToken)
broadcast-rcon-to-ops=false
level-name=world
level-type=minecraft\:flat
generator-settings={"layers":[{"block":"minecraft:bedrock","height":1},{"block":"minecraft:dirt","height":126},{"block":"minecraft:grass_block","height":1}],"biome":"minecraft:plains","structure_overrides":[]}
generate-structures=false
gamemode=creative
difficulty=normal
spawn-protection=0
view-distance=5
simulation-distance=5
max-players=8
motd=GoldCraft isolated development
"@ | Set-Content -LiteralPath $properties -Encoding utf8
    '# Local development runtime requested for this project.'+"`neula=true" | Set-Content -LiteralPath (Join-Path $server 'eula.txt') -Encoding ascii
}
$options=Join-Path $client 'options.txt'
if($Loader -eq 'neoforge' -and -not(Test-Path -LiteralPath $options)){
    $previous=Assert-SandboxPath (Join-Path $script:GoldCraftRoot "sandbox/minecraft-$Instance/options.txt")
    if(Test-Path -LiteralPath $previous){Copy-Item -LiteralPath $previous -Destination $options}
}
if(-not(Test-Path -LiteralPath $options)){
    @'
version:3953
onboardAccessibility:false
pauseOnLostFocus:false
renderDistance:5
simulationDistance:5
maxFps:60
enableVsync:false
fullscreen:false
soundCategory_master:0.6
guiScale:2
skipMultiplayerWarning:true
'@ | Set-Content -LiteralPath $options -Encoding utf8
}
& python (Join-Path $PSScriptRoot 'Prepare-HostWorlds.py') --loader $Loader
if($LASTEXITCODE){throw 'Host dimension preparation failed'}
