param(
    [ValidateSet('cs-client-a','cs-client-b')][string]$Instance='cs-client-b',
    [ValidateSet('neoforge','fabric')][string]$Loader='neoforge'
)
. (Join-Path $PSScriptRoot 'SandboxPaths.ps1')

$instanceRoot=Assert-SandboxPath (Join-Path $script:GoldCraftRoot "sandbox/$Instance")
$game=Assert-SandboxPath (Join-Path $instanceRoot 'Half-Life')
$config=Get-Content -LiteralPath (Join-Path $instanceRoot 'instance.json') -Raw | ConvertFrom-Json
if($config.game -ne $game){throw 'Instance path mismatch'}
foreach($relative in @('MetaHook.exe','cstrike/metahook/gamedata/index.json')){
    if(-not(Test-Path -LiteralPath (Join-Path $game $relative) -PathType Leaf)){
        throw "Complete this sandbox deployment first: $relative"
    }
}

# Explorer does not necessarily inherit the development shell's PowerShell PATH.
$powerShell=(Get-Command pwsh -CommandType Application -ErrorAction Stop | Select-Object -First 1).Source
$launchScript=Assert-WorkspacePath (Join-Path $PSScriptRoot 'Start-Sandbox.ps1')
$relativeScript=[IO.Path]::GetRelativePath($game,$launchScript)
$entry=Assert-SandboxPath (Join-Path $game 'Start-GoldCraft.cmd')
$batch=@'
@echo off
setlocal DisableDelayedExpansion
chcp 65001 >nul
rem Generated by tools/New-SandboxLauncher.ps1. Keep instance secrets in instance.json.
rem The managed launcher supplies -game cstrike, pairing and independent ports.
"{POWERSHELL}" -NoLogo -NoProfile -File "%~dp0{SCRIPT}" -Role CsClient -Instance {INSTANCE} -Loader {LOADER} -Wait
set "goldcraftExit=%errorlevel%"
if not "%goldcraftExit%"=="0" (
    echo GoldCraft client startup failed. See the error above and the instance logs.
    pause
)
exit /b %goldcraftExit%
'@
$batch=$batch.Replace('{POWERSHELL}',$powerShell.Replace('%','%%')).
    Replace('{SCRIPT}',$relativeScript.Replace('%','%%')).
    Replace('{INSTANCE}',$Instance).Replace('{LOADER}',$Loader)
[IO.File]::WriteAllText($entry,($batch -replace '\r?\n',"`r`n")+"`r`n",[Text.UTF8Encoding]::new($false))
Write-Output $entry
