if(NOT GOLDCRAFT_LLVM_ROOT)
    message(FATAL_ERROR "GOLDCRAFT_LLVM_ROOT must name the selected LLVM installation")
endif()
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES GOLDCRAFT_LLVM_ROOT)
set(CMAKE_C_COMPILER "${GOLDCRAFT_LLVM_ROOT}/bin/clang-cl.exe")
set(CMAKE_CXX_COMPILER "${GOLDCRAFT_LLVM_ROOT}/bin/clang-cl.exe")
set(CMAKE_LINKER "${GOLDCRAFT_LLVM_ROOT}/bin/lld-link.exe")
set(CMAKE_AR "${GOLDCRAFT_LLVM_ROOT}/bin/llvm-lib.exe")
set(CMAKE_LINKER_TYPE LLD)
set(CMAKE_C_FLAGS_INIT "--target=i686-pc-windows-msvc")
set(CMAKE_CXX_FLAGS_INIT "--target=i686-pc-windows-msvc")
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_PROJECT_INCLUDE "${CMAKE_CURRENT_LIST_DIR}/cxx20.cmake")
# O3 enables loop/vector optimization; ThinLTO optimizes across translation
# units. Do not use fast-math: collision and protocol code depend on finite/NaN
# checks and the established floating-point semantics. Renderer selects AVX2.
set(CMAKE_C_FLAGS_RELEASE_INIT "/O2 /clang:-O3 /clang:-flto=thin /arch:AVX2 /Gy /Gw /fp:precise /DNDEBUG")
set(CMAKE_CXX_FLAGS_RELEASE_INIT "${CMAKE_C_FLAGS_RELEASE_INIT}")
set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE_INIT}" CACHE STRING "GoldCraft Clang release optimization" FORCE)
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE_INIT}" CACHE STRING "GoldCraft Clang release optimization" FORCE)
set(CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT "/OPT:REF /OPT:ICF /OPT:LLDLTO=3")
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE_INIT "/OPT:REF /OPT:ICF /OPT:LLDLTO=3")
